GET http://localhost:3001/api/charts HTTP/1.1
###
GET http://localhost:3001/api/charts/ninni HTTP/1.1
###
GET http://localhost:3001/api/charts/ninni&1 HTTP/1.1
###
DELETE http://localhost:3001/api/charts/1 HTTP/1.1
###
POST http://localhost:3001/api/charts HTTP/1.1
content-type: application/json

{
    "id":6, 
    "age":"4", 
    "weight":5.285, 
    "name":"testiAPI"
}