GET http://localhost:3001/api/charts HTTP/1.1
###
GET http://localhost:3001/api/charts/2SD HTTP/1.1
###
GET http://localhost:3001/api/charts/ninni&1 HTTP/1.1
###
DELETE http://localhost:3001/api/charts/1 HTTP/1.1
###
POST http://localhost:3001/api/charts HTTP/1.1
content-type: application/json

{
    "age":"1", 
    "weight":5.6, 
    "name":"2SD"
}
